brew 'antidote'
brew 'colima'
brew 'colormake'
brew 'diff-so-fancy'
brew 'direnv'
brew 'docker'
brew 'docker-clean'
brew 'docker-compose'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'jq'
brew 'mas'
brew 'ripgrep'
brew 'starship'
brew 'tree'
brew 'uv'
brew 'watch'
brew 'yq'
brew 'yt-dlp'
brew 'zoxide'
brew 'zsh'
cask '1password'
cask '1password-cli'
cask 'alfred'
cask 'bbedit'
cask 'claude-code@latest'
cask 'codex'
cask 'deckset'
cask 'firefox'
cask 'font-source-code-pro'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-sans-3'
cask 'font-source-serif-4'
cask 'istat-menus'
cask 'kaleidoscope'
cask 'signal'
cask 'vlc'
mas '1Blocker', id: 1365531024
mas '1Password for Safari', id: 1569813296
mas '24 Hour Wallpaper', id: 1226087575
mas 'Adobe Lightroom', id: 1451544217
mas 'Codye', id: 1516894961
mas 'Fantastical', id: 975937182
mas 'GrandPerspective', id: 1111570163
mas 'Ivory', id: 6444602274
mas 'Keynote', id: 361285480
mas 'Magnet', id: 441258766
mas 'Microsoft Excel', id: 462058435
mas 'Microsoft PowerPoint', id: 462062816
mas 'Microsoft Word', id: 462054704
mas 'Numbers', id: 361304891
mas 'Pages', id: 361309726
mas 'Pixelmator Pro', id: 1289583905
mas 'Things', id: 904280696
mas 'WhatsApp', id: 310633997
