tap 'domt4/autoupdate'
brew 'ack'
brew 'antidote'
brew 'colima'
brew 'colormake'
brew 'diff-so-fancy'
brew 'direnv'
brew 'docker'
brew 'docker-clean'
brew 'docker-compose'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-extras'
brew 'github-keygen'
brew 'highlight'
brew 'hub'
brew 'jq'
brew 'mas'
brew 'pipx'
brew 'pyenv'
brew 'ripgrep'
brew 'rustup'
brew 'thefuck'
brew 'tree'
brew 'uv'
brew 'virtualenv'
brew 'watch'
brew 'yq'
brew 'yt-dlp'
brew 'zoxide'
brew 'zsh'
cask '1password'
cask '1password-cli'
cask 'alfred'
cask 'bbedit'
cask 'claude-code@latest'
cask 'codex'
cask 'deckset'
cask 'firefox'
cask 'font-source-code-pro'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-sans-3'
cask 'font-source-serif-4'
cask 'istat-menus'
cask 'kaleidoscope'
cask 'signal'
cask 'visual-studio-code'
cask 'vlc'
mas '1Blocker', id: 1365531024
mas '1Password for Safari', id: 1569813296
mas '24 Hour Wallpaper', id: 1226087575
mas 'Actions', id: 1586435171
mas 'Adobe Lightroom', id: 1451544217
mas 'Codye', id: 1516894961
mas 'Fantastical', id: 975937182
mas 'GrandPerspective', id: 1111570163
mas 'Ivory', id: 6444602274
mas 'Keynote', id: 409183694
mas 'Magnet', id: 441258766
mas 'Microsoft Excel', id: 462058435
mas 'Microsoft PowerPoint', id: 462062816
mas 'Microsoft Word', id: 462054704
mas 'MQTT Explorer', id: 1455214828
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Pixelmator Pro', id: 1289583905
mas 'Things', id: 904280696
mas 'WhatsApp', id: 310633997
mas 'Xcode', id: 497799835
vscode 'editorconfig.editorconfig'
vscode 'ms-azuretools.vscode-docker'
vscode 'ms-python.python'
vscode 'ms-python.vscode-pylance'
vscode 'ms-vscode-remote.remote-containers'
