export HOMEBREW_CLEANUP_MAX_AGE_DAYS=45
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=10
export HOMEBREW_NO_ENV_HINTS=1
export PG_COLOR=auto
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
export DATADOG_ROOT="$HOME/dd"
