export HOMEBREW_CLEANUP_MAX_AGE_DAYS=45
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=10
export HOMEBREW_NO_ENV_HINTS=1

export HOMEBREW_BUNDLE_FILE="${HOME}/.Brewfile"

# export JAVA_HOME="$(/usr/libexec/java_home)"
. "$HOME/.cargo/env"
