# display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

ZSH_DISABLE_COMPFIX="true"
ANTIGEN_COMPINIT_OPTS="-u"

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"

source "$(brew --prefix)/share/antigen/antigen.zsh"

antigen init ~/.antigenrc

# Dir: current working directory
prompt_dir() {
  prompt_segment blue $CURRENT_FG "$(shrink_path -f)"
}

#
# Variables
#

# Load standard Homebrew shellenv into the shell session.
# Load 'HOMEBREW_' prefixed variables only. Avoid loading 'PATH' related
# variables as they are already handled in standard zsh configuration.
if (( $+commands[brew] )); then
  eval "${(@M)${(f)"$(brew shellenv 2> /dev/null)"}:#export HOMEBREW*}"
fi

manp ()
{(
    set -o pipefail;
    gman -Tpdf "$@" | open -fa Preview
)}
alias ush='ssh -F/dev/null'
alias bb='bbedit'

source ~/.config/secrets-local

autoload -U compinit
compinit -u

# opam configuration
[[ ! -r /Users/jason/.opam/opam-init/init.zsh ]] || source /Users/jason/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
