#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

# Preferred editor for local and remote sessions.
export EDITOR='bbedit -w'
export VISUAL="${EDITOR}"
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Initialize Homebrew from its standard Apple Silicon or Intel location.
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -x4 -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ -n ${HOMEBREW_PREFIX:-} && -d ${HOMEBREW_PREFIX}/opt/postgresql@17/bin ]]; then
  path=("${HOMEBREW_PREFIX}/opt/postgresql@17/bin" $path)
fi

path=("${HOME}/.local/bin" $path)

if [[ -d "${HOME}/.trajectory/bin" ]]; then
  path=("${HOME}/.trajectory/bin" $path)
fi

[[ -r "$HOME/.privilegesalias" ]] && source "$HOME/.privilegesalias"
